influxdbData:
  image: busybox
  volumes:
    - ./data/influxdb:/data

influxdb:
  image: tutum/influxdb:0.9
  environment:
    - PRE_CREATE_DB=telegraf
  ports:
    - "8083:8083"
    - "8086:8086"
  expose:
    - "8090"
    - "8099"
  volumes_from:
    - "influxdbData"

telegraf:
  build: ./docker-monitoring/telegraf/1.0
  dockerfile: Dockerfile
  links:
    - influxdb:influxsrv
  volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
  ports:
    - "8094:8094"
  command: -config telegraf.conf -input-filter cpu:mem -output-filter influxdb

grafana:
  image: grafana/grafana:3.0.3
  links:
    - influxdb:influxsrv
  ports:
    - "3000:3000"
  environment:
    - HTTP_USER=admin
    - HTTP_PASS=admin
    - INFLUXDB_HOST=influxsrv
    - INFLUXDB_PORT=8086
    - INFLUXDB_NAME=telegraf
    - INFLUXDB_USER=root
    - INFLUXDB_PASS=root
